services:
  app:
    build:
      context: ./../
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./../menu_planner:/app/menu_planner
      - ./../frontend:/var/www/frontend:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DATABASE_URL=postgresql://menu_planner:menu_planner@db/menu_planner
    ports:
      - "8000:8000"  # Exposes the app to the Nginx proxy
      - "80:80"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: menu_planner
      POSTGRES_PASSWORD: menu_planner
      POSTGRES_DB: menu_planner
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
